# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

sudo: false
language: python
virtualenv:
  system_site_packages: true
matrix:
  include:
    - python: 3.4
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py34" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
install:
  - source tests/travis_install.sh
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - pip list
  - python setup.py develop
  - tox -e all
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true
  directories:
    - $HOME/miniconda
